(ENG-822) Format menu data
Thistle/galley-sdk pull request #18
Opened 2021-11-11 21:03 UTC by thunguy

## Description
This PR is focused on formatting menu data returned from `get_week_menu_data` by creating a wrapper function, `get_formatted_menu_data`. 

## Test Plan
Open python interactive within galley-sdk: `$ python`
`>>> from pprint import pprint` (optional: to apply pretty print format to returned data)
`>>> from galley.queries import *` 

### 1. All valid menu names passed in, and **_all_** include 'standalone' items:
`>>> pprint(get_formatted_menu_data(["2021-10-04 1_2_3", "2021-10-25 1_2_3"]))`

> **Expectation:** A return value **similar** to:
> ```python3
> [
>  {'name': '2021-10-04 1_2_3',
>   'date': '2021-10-04',
>   'id': 'bWVudTo2MzQ2NTY=',
>   'location': 'Vacaville',
>   'menuItems': [{'itemCode': 'dv3',
>                   'recipeId': 'cmVjaXBlOjE3ODAxMA==',
>                   'standaloneRecipeId': 'cmVjaXBlOjE3NDQxMg=='},
>                  {'itemCode': 'dm1',
>                   'recipeId': 'cmVjaXBlOjE3NjQ5Mg==',
>                   'standaloneRecipeId': 'cmVjaXBlOjE3NjQ4OQ=='},
>                  {'itemCode': 'dv1',
>                   'recipeId': 'cmVjaXBlOjE3NjQ4Mg==',
>                   'standaloneRecipeId': 'cmVjaXBlOjE3NjQ4OQ=='}]},
>  {'name': '2021-10-25 1_2_3',
>   'date': '2021-10-25',
>   'id': 'bWVudTo3NjM2MjA=',
>   'location': 'Vacaville',
>   'menuItems': [{'itemCode': 'dv1',
>                   'recipeId': 'cmVjaXBlOjE3OTk1Mw==',
>                   'standaloneRecipeId': 'cmVjaXBlOjE3NDI2MQ=='},
>                  {'itemCode': None,
>                   'recipeId': 'cmVjaXBlOjE4MjI0NQ==',
>                   'standaloneRecipeId': 'cmVjaXBlOjE3NDI2MQ=='},
>                  {'itemCode': 'dm1',
>                   'recipeId': 'cmVjaXBlOjE3OTk2MA==',
>                   'standaloneRecipeId': 'cmVjaXBlOjE3NDI2MQ=='},
>                  {'itemCode': 'lv3',
>                   'recipeId': 'cmVjaXBlOjE4MDU1OA==',
>                   'standaloneRecipeId': 'cmVjaXBlOjE2OTE1Ng=='}]}
> ]
>```

### 2. All valid menu names passed in, but only **_some_** include 'standalone' items:
`>>> pprint(get_formatted_menu_data(["2021-10-04 1_2_3", "2021-10-04 4_5_6", "2021-10-25 1_2_3", "2021-10-25 4_5_6"]))`

> **Expectation:** Since only **'2021-10-04 1_2_3'** and **'2021-10-25 1_2_3'** have 'standalone' items, return value should be the same as the one above

### 3. All valid menu names passed in, but **_none_** include 'standalone' items:
`>>> pprint(get_formatted_menu_data(["2021-10-04 4_5_6", "2021-10-25 4_5_6"]))`

> **Expectation:** A return value of `[]`

### 4. Invalid or no menu names passed in:
`>>> pprint(get_formatted_menu_data(["invalid-menu-name 4_5_6"]))`
`>>> pprint(get_formatted_menu_data([]))`

> **Expectation:** A return value of `None`

### 5. Run unittests
Exit python interactive and stay within the galley-sdk directory to run tests:
`(galley-env) $ python -m unittest tests/test_queries.py`
**[OPTIONAL SANITY CHECK]** `(galley-env) $ python -m unittest tests/test_*.py`

## Versioning
v0.9.0 -> v0.10.0

2021-11-15 18:18 UTC, drewdas requested changes

2021-11-15 18:18 UTC, drewdas commented on tests/test_queries.py
> +        mock_retrieval_method.side_effect = [
why is this a side effect? as the method is being mocked here it should be a return_value, usually side effects are used for raising exceptions

2021-11-15 18:18 UTC, drewdas commented on tests/test_queries.py
> +        result = get_formatted_menu_data([])
if the return value is none, wouldnt None be passed to the method get_formatted_menu_data ?

2021-11-15 18:18 UTC, drewdas commented on galley/queries.py
> +    menus = get_week_menu_data(names)
we are already formatting the data in get_week_menu_data by calling the method validate_response_data, if we have agreed that this is how the menu data should be formatted, should we consider just formatting the data before its returned in get_week_menu_data itself?

2021-11-15 18:18 UTC, drewdas commented on galley/queries.py
> +            'name': menu.get('name'),
do we want getting the keys here to fail silently? for example if 
`a = {}` `a.get('name')` would just return `None` hiding the issue that the data is missing the key. if we are expecting the data to contain certain keys we should have it throw KeyError so that we can handle that exception. here's an example.

```
try:
    name = menu['name']
except KeyError:
    logger.error('menu data for date x is missing key "name"')
    name = ""
```

this way the method would still return blank values if key does not exist but if we were investigating why menu data is missing a certain piece of data we can actually check the logs.

if you think a key is crucial such then the method should just raise an exception and not return a blank value.

2021-11-15 18:26 UTC, thunguy commented on tests/test_queries.py
> +        mock_retrieval_method.side_effect = [
I used side effect here to return a different value every call.

2021-11-15 18:27 UTC, thunguy commented on tests/test_queries.py
> +        mock_retrieval_method.side_effect = [
https://docs.python.org/3/library/unittest.mock.html#:~:text=side_effect%3A%20A%20function,the%20return%20value.

2021-11-15 19:25 UTC, thunguy commented on tests/test_queries.py
> +        result = get_formatted_menu_data([])
We can't explicitly pass a `None` type into `get_formatted_menu data()`.

2021-11-15 19:33 UTC, thunguy commented on tests/test_queries.py
> +        result = get_formatted_menu_data([])
If the data is None, then it gets implicitly handled by `validate_response_data()` https://github.com/Thistle/galley-sdk/blob/5f5e8b178595b9002f36772924c14898ea4d070f/galley/common.py#:~:text=def%20validate_response_data(data,return%20None

2021-11-15 19:33 UTC, thunguy commented on tests/test_queries.py
> +        result = get_formatted_menu_data([])
Would it be more appropriate to change the name of the test function?

2021-11-15 19:38 UTC, thunguy commented on galley/queries.py
> +    menus = get_week_menu_data(names)
I believe the reason why we don't want to modify the original query function, and instead create a wrapper function, is because we want to account for the different data we'll need returned, say for thistle-web vs. okra for example.

2021-11-15 19:40 UTC, thunguy commented on galley/queries.py
> +    menus = get_week_menu_data(names)
It's also in the notes  for the ticket that it should be split out into its own wrapper function. 

Explanation being: 

> "Instead of updating get_week_menu_data()directly, we most likely want to create a wrapper function to handle the formatting. The wrapper function is what would be called by a consuming service like thistle-web, and would itself call get_week_menu_data(). This is a pattern we have started with recipe ingredient data, via get_formatted_recipe_ingredients().  Doing this will make it easier to move the formatting code over to thistle-web, if we decide later that we'd rather have the formatting happen there." 

https://linear.app/thistle/issue/ENG-822/format-menu-data#:~:text=Instead%20of%20updating,formatting%20happen%20there.

2021-11-15 19:52 UTC, thunguy commented on galley/queries.py
> +            'name': menu.get('name'),
This makes sense in case it fails on our end. For context, it's required that all the fields within `formatted_menu` (minus `date`) are non-nullable on the Galley side.

2021-11-15 22:10 UTC, thunguy commented on galley/queries.py
> +            'name': menu.get('name'),
I'm not necessarily sure if we should have them return as empty strings, but I could be wrong! @mollykmcglone What do you think?

2021-11-15 22:25 UTC, thunguy commented on tests/test_queries.py
> +        mock_retrieval_method.side_effect = [
https://docs.python.org/3/library/unittest.mock.html#:~:text=If%20side_effect%20is%20an%20iterable%20then%20each%20call%20to%20the%20mock%20will%20return%20the%20next%20value%20from%20the%20iterable.

2021-11-15 23:34 UTC, mollykmcglone commented on galley/queries.py
> +            'name': menu.get('name'),
I think this is a case where we want to support the happy path for now and come back later to add handling for missing data. We will need to do the same at the recipe level as well.

2021-11-16 02:09 UTC, drewdas commented on tests/test_queries.py
> +        result = get_formatted_menu_data([])
yeah I think I got confused by the name 😄

2021-11-16 02:10 UTC, drewdas commented on galley/queries.py
> +            'name': menu.get('name'),
sounds good to me, we are checking validity in a method at a higher level so I'm fine with that

2021-11-16 02:12 UTC, drewdas commented on galley/queries.py
> +    menus = get_week_menu_data(names)
ah I see, thank you

2021-11-16 02:12 UTC, drewdas approved these changes
LGTM

2021-11-16 22:50 UTC, merged