VEG-249: update ingredient handling
Thistle/galley-sdk pull request #73
Opened 2022-10-28 00:01 UTC by kate-skorija

## Description
Please include a summary of the change. List any dependencies that are required for this pull request.

## Test Plan
1. In Galley staging, pull up a recipe like [Cuban Ropa Vieja with Plantains and Jackfruit Ropa Vieja](https://staging-app.galleysolutions.com/recipes/cmVjaXBlOjE4NTUxMA==?userLocationId=bG9jYXRpb246MTkyOA%3D%3D) that has base recipe, and sub recipes with multiple vendor items.
2. Navigate to a location specific vendor item (West or East Coast) for a sub recipe, and add ingredients to the ingredients list field. Repeat for another sub recipe. 
3. In the galley-sdk virtual environment, call `get_formatted_recipes_data` and `get_raw_recipes_data` with the recipe id and location name of the vendor item you modified. Example queries for Cuban Ropa Vieja, Burlington:
```
import galley
from galley.queries import *
from galley.formatted_queries import *

get_raw_recipes_data(recipe_ids=['cmVjaXBlOjE4NTUxMA==], location_name='Burlington')
get_formatted_recipes_data(recipe_ids=['cmVjaXBlOjE4NTUxMA=='], location_name='Burlington')

```
4. Verify that your modifications from Galley are present in the results. 
 - For `get_raw_recipes_data`, the ingredient list items you added  should be present in square brackets after the ingredient at the sub recipe level. 
 - For the `get_formatted_recipes_data` result, the ingredient list items you added should be present in parenthesis after the ingredient.  
5. Repeat these calls with the opposite location name, and verify that the return data matches what is in Galley for that location. 
## Versioning
0.43.0

2022-10-28 02:03 UTC, jamie-smyth-at-thistle reviewed
In general this looks good but I do find the nested conditionals a little complex and difficult to follow. 

Also generally consider adding type hints to function signatures.

2022-10-28 06:11 UTC, thunguy commented on galley/formatted_queries.py
> +
> But I must admit I don't know the intended logic nor am I sure what get does if the property exists but is None so there might be some other caveats there.

Chaining a `.get()` to a key value of `None` will throw an AttributeError. Going from js optional chaining back to Python has made me bitter towards `.get()` because it just doesn't need to be so verbose. However, I do use it and when I do, I prefer to handle both cases in one--if key doesn't exist or if the key value is `None`--by using the 'or' operator. In other words, it's just declaring 'if falsy anyways, return this falsy (or non-falsy) thing over this other falsy thing': 

```python3
# verbose but can be easier to read
location_vendor_items = ingredient.get('locationVendorItems') or {}
vendor_items = location_vendor_items.get('vendorItems') or []
```
or 
```python3
# shorter but can be 
>>> ingredient = {}
>>> (ingredient.get('locationVendorItems') or {}).get('vendorItems') or [] 
[]

>>> ingredient = {"locationVendorItems": None}
>>> (ingredient.get('locationVendorItems') or {}).get('vendorItems') or [] 
[]

>>> ingredient = {"locationVendorItems": {}}
>>> (ingredient.get('locationVendorItems') or {}).get('vendorItems') or [] 
[]

>>> ingredient = {"locationVendorItems": {"vendorItems": []}}
>>> (ingredient.get('locationVendorItems') or {}).get('vendorItems') or []
[]

>>> ingredient = {"locationVendorItems": {"vendorItems": None}}
>>> (ingredient.get('locationVendorItems') or {}).get('vendorItems') or []
[]

>>>  ingredient = {"locationVendorItems": {"vendorItems": ["vendor item 1", "vendor item 2"]}}
>>> (ingredient.get('locationVendorItems') or {}).get('vendorItems') or []
['vendor item 1', 'vendor item 2']

# If ingredient is None, you can combo with a python ternary if you don't find it too excessive
>>> ingredient = None
>>> (ingredient.get('locationVendorItems') or {}).get('vendorItems') or [] if ingredient else []
[]

# Personally, I prefer to split the one above over two lines
if ingredient:
    vendor_items = (ingredient.get('locationVendorItems') or {}).get('vendorItems') or []
```

2022-10-28 22:30 UTC, dip-thistle commented on galley/formatted_queries.py
> +
@ErikBrown, I do like @jamie-smyth-at-thistle and @thunguy 's suggestions here. I think Jamie's approach is much more cleaner and readable. I think this is a good place to adapt some good practice. 

I would not use another library just to get the first element from a list or dict. I think using built in `next()` method should be enough for our requirements. I also checked that using `next()` does not add too much processing time I don't have exact comparison between `List[0]` and `next()`but it was negligible.

2022-10-28 23:28 UTC, thunguy commented on galley/formatted_queries.py
> +
@dip-thistle List[0] should always have a faster runtime than next() because calling a value in a list by index is O(1) constant time, whereas next() is O(n) given that if the length of your list increases, so does the runtime since it requires traversing through the list to get the value you're trying to find. Although, if your list is fairly small, it really shouldn't matter. My comment above was just a reply to @jamie-smyth-at-thistle to show what happens when you call `.get()` on a None value, and _a_ solution on how to get around it using `.get()`, but not necessarily saying that should be the adopted method.

2022-10-28 23:34 UTC, thunguy commented on galley/formatted_queries.py
> +def get_external_name_for_ingredient(data_dict):
I agree with @jamie-smyth-at-thistle here as well. We should be type hinting where we can.

2022-10-28 23:45 UTC, dip-thistle commented on galley/formatted_queries.py
> +
Yeah if it were to be long list (> 5) then I would have not have suggested using `next()`.

2022-10-28 23:54 UTC, thunguy commented on galley/formatted_queries.py
> +
@dip-thistle Agreed!

2022-10-29 00:16 UTC, jamie-smyth-at-thistle commented on galley/formatted_queries.py
> +
@thunguy I was actually experimenting with the use of the `or` operator just like you have in the example and end up with an even more concise implementation.  I just wasn't sure if that use of `or` was an accepted way of doing things in python.

So I thought about the logic like this
```
"external name" or "name" plus "ingredient str" if exists
```

This is slightly different than the current implementation as it will append the "ingredient str" even if there is only "name" and not "external name", but I'm not convinced this isn't the correct way anyway. So then I ended with an implementation like.
```python
def get_external_name_for_ingredient(ingredient: Dict) -> Optional[str]:
    
    name =  (ingredient.get("externalName") or ingredient.get("name"))
    ingredientListStr = (get_primary_vendor_item_for_ingredient(ingredient) or {}).get("ingredientListStr")
    return f"{name} ({ingredientListStr})" if name and ingredientListStr else name

def get_primary_vendor_item_for_ingredient(ingredient: Dict) -> Optional[Dict]:
    vendorItems = next(iter(ingredient.get('locationVendorItems',[])),{}).get('vendorItems',[])
    return (
        next((vendorItem for vendorItem in vendorItems if vendorItem.get('priority') == 0 and vendorItem['ingredientListStr']),None)
        or next(iter(vendorItems), None)
    )
```
This passes all the test.  I could probably shrink the `get_primary_vendor_item_for_ingredient` into a single line as well, but no need to get too clever ™️ .

2022-10-29 01:25 UTC, jamie-smyth-at-thistle commented on galley/formatted_queries.py
> +
Now to address the question of performance. `next` is actually O(1) performance as no iteration takes place. It simply gets the element at the current iterators index. This is effectively the same as calling `iter[0]` This can be proven with the following benchmark
https://perfpy.com/133

Now looking at comparison benchmarks between `list[0]` and `next` we do see some difference.  I compared all of the following.
```python
first = list[0] # get first by index
first = list[0] if list else None # get first while safely handling None and empty lists
first = next(iter, None) # using next and safely handling empty iterat
first = next(iter(list), None) # using next but creating an iterator each time
```
https://perfpy.com/134

Yes using the safe version by index is slighty faster than getting the safe version with an existing iterator.

Now I wanted to see how the performance was if you compare using an iter directly or converting the iter to a list and getting the first by index.
I compared the following two snipets
```python
first = [item for item in list1][0] if list1 else None
first = next(item for item in list1, None)
```
https://perfpy.com/135

What we find here is that using next is orders of magnitude faster, and this is because the list comprehension is an O(n) operation . So if you already have an iterator (say from filtering a list), you are **much** better off using next

My point here isn't actually to nit pick about performance.  We do list comprehension all over the place without batting an eye at the performance impact. My point is actually that clarity can some times take precedence over performance.

So here are what I see as the options for getting the first element safely from a list
If we are not looping the list such as for filtering
```python
first = list[0] if list or None # safe and fastest but contains a magic number 
first = next(iter(list), None) # safe with no magic number but would be a pattern we would have to get used to
first = first(list) # fast, safe and clear
```

When working with iterators, such as the result of filtering a list
```python
first = [item for item in list][0] if list or None # safe but very slow on large lists and contains a magic number
first = next(item for item in list, None) # safe with no magic number and blazingly fast but not as clear as can be
first = first(item for item in list) # fast safe and clear
```

@dip-thistle do you not think it's worth using a library for clarity?

2022-10-31 18:30 UTC, dip-thistle commented on galley/formatted_queries.py
> +
@jamie-smyth-at-thistle I looked at the library there is not much logic, Could we just write our own helper method instead? 

The last version was released in 2019. So I am not sure how maintained `first` library is.

2022-10-31 18:32 UTC, dip-thistle commented on galley/formatted_queries.py
> +
It is very simple implementation so I don't think this library needs much maintenance but still just a thought!

2022-10-31 20:17 UTC, kate-skorija commented on tests/test_queries.py
> +        self.assertEqual(location_id_value, 'test')
I've added this change

2022-10-31 20:17 UTC, kate-skorija commented on tests/test_formatted_queries.py
> +        self.assertEqual(result, expected_ing_str)
That makes much more sense :) thanks for the suggestion

2022-10-31 20:21 UTC, kate-skorija commented on galley/formatted_queries.py
> +def get_external_name_for_ingredient(data_dict):
I tend to forget to add type hinting, thank you both for the reminder!

2022-10-31 20:25 UTC, kate-skorija commented on galley/formatted_queries.py
> +
Thank you all for your contributions on this! I've added Jamie's suggested implementation, but did have to change the `get_primary_vendor_item_for_ingredient` function slightly to avoid linting errors. I was getting the following error ```galley/formatted_queries.py:27: error: No overload variant of "get" of "Mapping" matches argument types "str", "List[<nothing>]"``` before I separated getting `vendorItems` into two lines, as well as errors about needing type annotation for the `vendorItems` and `locationVendorItems` variables.

2022-10-31 20:52 UTC, jamie-smyth-at-thistle requested changes
I knew you took the code I suggested, but there where a couple potential miss in that code as I don't know the details of the source of data.  So I left a few Non-Blocking(NB) suggestions, one question and a request to add a missing test scenario.

2022-10-31 20:52 UTC, jamie-smyth-at-thistle commented on galley/formatted_queries.py
> +    vendorItems: List = locationVendorItems.get('vendorItems',[])
NB: This will error if `vendorItems` is `None`.  If it's possible for this property to be `None` we might want to consider the following instead.
```suggestion
    vendorItems: List = locationVendorItems.get('vendorItems') or []
```
This will handle none exiting property as well as `None`.  It won't handle a value of the wrong type(not a List), but arguable that should be an exception (or we should used typed objects rather than dicts)

2022-10-31 20:52 UTC, jamie-smyth-at-thistle commented on galley/formatted_queries.py
> +    name = (ingredient.get("externalName") or ingredient.get("name"))
I assume you double checked that we would want to append the `ingredientListStr` even if there is no `externalName`.  I know the original logic didn't follow this pattern.

2022-10-31 20:52 UTC, jamie-smyth-at-thistle commented on galley/formatted_queries.py
> +    locationVendorItems: Dict = next(iter(ingredient.get('locationVendorItems',[])),{})
NB: This will error if `locationVendorItems` is `None`.  If it's possible for this property to be `None` we might want to consider the following instead.
```suggestion
    locationVendorItems: Dict = next(iter(ingredient.get('locationVendorItems') or []),{})
```
This will handle none exiting property as well as None. It won't handle a value of the wrong type (not a List), but arguable that should be an exception (or we should used typed objects rather than dicts)

2022-10-31 20:52 UTC, jamie-smyth-at-thistle commented on tests/test_formatted_queries.py
> +class TestIngredientExternalName(TestCase):
I think there is one test missing here that might answer one of the above questions. That would be a test to cover what happens if there is a name, no external name, with an ingredientStrList.

- [ ] Add test to cover case where there is a name, no external name but with an ingredientStrList

2022-10-31 21:18 UTC, patrick-thistle reviewed
Test of functionality looks good.

This will be ready to go once request changes have been resolved.

2022-10-31 21:41 UTC, kate-skorija commented on galley/formatted_queries.py
> +    name = (ingredient.get("externalName") or ingredient.get("name"))
I did confirm, thanks for double checking

2022-10-31 21:41 UTC, kate-skorija commented on galley/formatted_queries.py
> +    locationVendorItems: Dict = next(iter(ingredient.get('locationVendorItems',[])),{})
added the `or`, thanks for the suggestion

2022-10-31 21:42 UTC, kate-skorija commented on tests/test_formatted_queries.py
> +class TestIngredientExternalName(TestCase):
Added

2022-10-31 22:34 UTC, patrick-thistle approved these changes
Functionally this works great.

Approving, please hold merge pending resolution of remaining comments.

2022-11-01 18:21 UTC, jamie-smyth-at-thistle approved these changes
Looks good to me.

2022-11-01 18:23 UTC, jamie-smyth-at-thistle commented on tests/test_formatted_queries.py
> +        ingredient = {
This is maybe a bigger picture question, so no need to hold up this PR

2022-11-01 19:55 UTC, merged